export const details = [
  {
    id: 0,
    image: "",
    file: "",
    name: "N Nijin",
    email: "nijinnazar26@gmail.com",
    dob: "26-08-2000",
    marExams: 1,
    aprExams: 0,
    table1: {
      sno: 1,
      courseName: "User Interface Design",
      examDate: "26-03-2023",
      session: "Afternoon",
      examType: "online",
      centreName: "iON Digital Zone iDZ Kollam",
      centreAddress:
        "Sree Buddha Center for Information and Technology, Kallumthazham PO, Near Palkulangara Bhagavathi Temple, Kollam, Kerala, India, 691004",
      examFeedback: "",
      scoreFeedback: "",
    },
    table2: {
      timeline: "Jan-Feb 2023",
      name: "N NIJIN",
      courseName: "User Interface Design",
      assignmentScore: "17.25",
      examScore: "31.13",
      finalScore: "48",
      viewDetails: "Click here",
    },
  },
  {
    id: 1,
    image: "",
    file: "https://drive.google.com/uc?export=download&id=15M_QClJ5VExoQiSvvpOGsy7MsgcJlZyf",
    name: "Muhammad Riswan",
    email: "mhdriswan41@gmail.com",
    dob: "14-08-2001",
    marExams: 1,
    aprExams: 0,
    table1: {
      sno: 1,
      courseName: "User Interface Design",
      examDate: "26-03-2023",
      session: "Afternoon",
      examType: "online",
      centreName: "iON Digital Zone iDZ Kollam",
      centreAddress:
        "Sree Buddha Center for Information and Technology, Kallumthazham PO, Near Palkulangara Bhagavathi Temple, Kollam, Kerala, India, 691004",
      examFeedback: "",
      scoreFeedback: "",
    },
    table2: {
      timeline: "Jan-Feb 2023",
      name: "MUHAMMAD RISWAN",
      courseName: "User Interface Design",
      assignmentScore: "18.25",
      examScore: "31.11",
      finalScore: "42",
      viewDetails: "Click here",
    },
  },
];
