export const details = [
  {
    id: 0,
    image: "",
    file: "",
    name: "N Nijin",
    email: "nijinnazar26@gmail.com",
    dob: "26-08-2000",
    marExams: 1,
    aprExams: 0,
    table1: {
      sno: 1,
      courseName: "User Interface Design",
      examDate: "26-03-2023",
      session: "Afternoon",
      examType: "online",
      centreName: "iON Digital Zone iDZ Kollam",
      centreAddress:
        "Sree Buddha Center for Information and Technology, Kallumthazham PO, Near Palkulangara Bhagavathi Temple, Kollam, Kerala, India, 691004",
      examFeedback: "",
      scoreFeedback: "",
    },
    table2: {
      timeline: "Jan-Feb 2023",
      name: "N NIJIN",
      courseName: "User Interface Design",
      assignmentScore: "17.25",
      examScore: "31.13",
      finalScore: "48",
      viewDetails: "Click here",
    },
  },
  {
    id: 1,
    image: "",
    file: "https://drive.google.com/uc?export=download&id=15M_QClJ5VExoQiSvvpOGsy7MsgcJlZyf",
    name: "Muhammad Riswan",
    email: "mhdriswan41@gmail.com",
    dob: "14-08-2001",
    marExams: 1,
    aprExams: 0,
    table1: {
      sno: 1,
      courseName: "User Interface Design",
      examDate: "26-03-2023",
      session: "Afternoon",
      examType: "online",
      centreName: "iON Digital Zone iDZ Kollam",
      centreAddress:
        "Sree Buddha Center for Information and Technology, Kallumthazham PO, Near Palkulangara Bhagavathi Temple, Kollam, Kerala, India, 691004",
      examFeedback: "",
      scoreFeedback: "",
    },
    table2: {
      timeline: "Jan-Feb 2023",
      name: "MUHAMMAD RISWAN",
      courseName: "User Interface Design",
      assignmentScore: "18.25",
      examScore: "31.11",
      finalScore: "42",
      viewDetails: "Click here",
    },
  },
  {
    id: 2,
    image: "",
    file: "https://drive.google.com/uc?export=download&id=1JLX-776A4w4TisqoBVHyYYh3sU071R0V",
    name: "Anush A",
    email: "anushanirudh001@gmail.com",
    dob: "23-01-2001",
    marExams: 1,
    aprExams: 0,
    table1: {
      sno: 1,
      courseName: "Enhancing Soft Skills and Personality",
      examDate: "24-04-2022",
      session: "forenoon",
      examType: "online",
      centreName: "iON Digital Zone iDZ Kollam",
      centreAddress:
        "Sree Buddha Center for Information and Technology, Kallumthazham PO, Near Palkulangara Bhagavathi Temple, Kollam, Kerala, India, 691004",
      examFeedback: "",
      scoreFeedback: "",
    },
    table2: {
      timeline: "Feb-Apr 2022",
      name: "ANUSH A",
      courseName: "Enhancing Soft Skills and Personality",
      assignmentScore: "19.2",
      examScore: "38",
      finalScore: "58",
      viewDetails: "Click here",
    },
  },
  {
    id: 3,
    image: "",
    file: "https://drive.google.com/uc?export=download&id=18GAOJRBdolV9zXWXgzIs-uUgQKlXPhYV",
    name: "H Abhijith Lal",
    email: "abhijithlalharivaram@gmail.com",
    dob: "31-03-2001",
    marExams: 1,
    aprExams: 0,
    table1: {
      sno: 1,
      courseName: "User Interface Design",
      examDate: "26-03-2023",
      session: "forenoon",
      examType: "online",
      centreName: "iON Digital Zone iDZ Kollam",
      centreAddress:
        "Sree Buddha Center for Information and Technology, Kallumthazham PO, Near Palkulangara Bhagavathi Temple, Kollam, Kerala, India, 691004",
      examFeedback: "",
      scoreFeedback: "",
    },
    table2: {
      timeline: "Jan-Feb 2023",
      name: "H Abhijith Lal",
      courseName: "User Interface Design",
      assignmentScore: "17.8",
      examScore: "31.1",
      finalScore: "43",
      viewDetails: "Click here",
    },
  },
  {
    id: 4,
    image: "",
    file: "https://drive.google.com/uc?export=download&id=1OMT97We52pqREJEtBu7cpsVR3PcHdKsV",
    name: "Madhav M Mohan",
    email: "madhavmohan23@gmail.com",
    dob: "23-10-2001",
    marExams: 1,
    aprExams: 0,
    table1: {
      sno: 1,
      courseName: "User Interface Design",
      examDate: "26-03-2023",
      session: "forenoon",
      examType: "online",
      centreName: "iON Digital Zone iDZ Kollam",
      centreAddress:
        "Sree Buddha Center for Information and Technology, Kallumthazham PO, Near Palkulangara Bhagavathi Temple, Kollam, Kerala, India, 691004",
      examFeedback: "",
      scoreFeedback: "",
    },
    table2: {
      timeline: "Jan-Feb 2023",
      name: "MADHAV M MOHAN",
      courseName: "User Interface Design",
      assignmentScore: "17",
      examScore: "32.4",
      finalScore: "49",
      viewDetails: "Click here",
    },
  },
  {
    id: 5,
    image: "",
    file: "https://drive.google.com/uc?export=download&id=101n3HDhq09SpRl7eWBpw7v5O56Dq8Im5",
    name: "Lakshmi Anil",
    email: "lakshmianil252@gmail.com",
    dob: "21-08-2001",
    marExams: 1,
    aprExams: 0,
    table1: {
      sno: 1,
      courseName: "User Interface Design",
      examDate: "26-03-2023",
      session: "forenoon",
      examType: "online",
      centreName: "iON Digital Zone iDZ Kollam",
      centreAddress:
        "Sree Buddha Center for Information and Technology, Kallumthazham PO, Near Palkulangara Bhagavathi Temple, Kollam, Kerala, India, 691004",
      examFeedback: "",
      scoreFeedback: "",
    },
    table2: {
      timeline: "Jan-Feb 2023",
      name: "LAKSHMI ANIL",
      courseName: "User Interface Design",
      assignmentScore: "19.2",
      examScore: "35.3",
      finalScore: "49",
      viewDetails: "Click here",
    },
  },
  {
    id: 6,
    image: "",
    file: "https://drive.google.com/uc?export=download&id=1ANEI77srGyxTcrecejsiEACS2n57xwSP",
    name: "Gopika S",
    email: "gopikasanthosh234@gmail.com",
    dob: "08-03-2001",
    marExams: 1,
    aprExams: 0,
    table1: {
      sno: 1,
      courseName: "Effective Writing",
      examDate: "26-03-2023",
      session: "afternoon",
      examType: "online",
      centreName: "Mount Carmel Residential School, Thiruvananthapuram",
      centreAddress:
        "Mount Carmel Residential School, Kanjiramkulam P O, Thiruvananthapuram, Kerala, India 695524",
      examFeedback: "",
      scoreFeedback: "",
    },
    table2: {
      timeline: "Jan-Feb 2023",
      name: "GOPIKA S",
      courseName: "Effective Writing",
      assignmentScore: "19.2",
      examScore: "41",
      finalScore: "60",
      viewDetails: "Click here",
    },
  },
];
